[package]
name = "access-control-multisig"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "AccessControlMultisig - Roles (OWNER / UPGRADER / PAUSER / WRITER) with optional Stellar native multisig 2/3 threshold."
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
testutils = []

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
